### PR TITLE
Add support for Docusaurus 3.0.0

### LINKED ISSUE #123: Support docusaurus 3
I'm currently in the process of exploring upgrading our docusaurus instance to v3.0.0-rc.1. To do so I've had to override a few of the peer-dependencies in docusaurus-lunr-search.

```json
"docusaurus-lunr-search": {
  "@docusaurus/core":  "$@docusaurus/core",
  "react":  "$react",
  "react-dom":  "$react-dom"
}
``` 

I believe the proper "solution" to this would be to update the package.json to also support `react ^18` and `docusaurus ^3.0.0-rc.1`.

### PR DESCRIPTION
**Pull request by Hinton**
This adds support for Docusaurus 3.0.0 by expanding the peer dependencies.

Resolves #123

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Please merge this, we need this!

**Comment by wgruszczyk** [comment]
@Hinton After migrating to 3.3.0 I get a lot issues alike:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')
    at a.getTitleHit (271.d685c5ef.js:1:811)
    at 271.d685c5ef.js:1:2166
    at Array.forEach (<anonymous>)
    at 271.d685c5ef.js:1:1985
    at new Promise (<anonymous>)
    at a.search (271.d685c5`

Did you experience the same? Maybe you can suggest a workaround?
Thx!

**Comment by wgruszczyk** [comment]
OK, nevermind. I had a swizzled version of the search component. Removed it and it works like a charm. Thx!

**Comment by windhamdavid** [comment]
@wgruszczyk - just wanted to add some additional context here to make it a bit more discoverable and easy to fix.

- If you previously `swizzle`'d a `SearchBar` in a prior version `<= v.2.2`:
```console
foo@bar:~$ npm run swizzle docusaurus-lunr-search SearchBar -- --danger
```
- You need to `eject` it before your build for `>= v.3.0`:
```console
foo@bar:~$ npm run swizzle docusaurus-lunr-search SearchBar -- --eject
```
Thanks for the effort @Hinton & @praveenn77 👊🏼

**Pull request merged**
