### PR TITLE
Fix plugin for Docusuarus 2.1.0

### LINKED ISSUE #85: Search does not work with latest Docusaurus v2
I followed the instructions on the README but the lunr apis return no results...

### LINKED ISSUE #87: Installation fails with Docusaurus v2.0
When following the installation steps the `swizzle` script runs into an error:
```sh
npx create-docusaurus@latest my-website classic
...
cd my-website
npm i docusaurus-lunr-search  --save
npm install
npm run swizzle docusaurus-lunr-search SearchBar -- --danger

> my-website@0.0.0 swizzle
> docusaurus swizzle "docusaurus-lunr-search" "SearchBar" "--danger"

[ERROR] Theme docusaurus-lunr-search not found. Themes available for swizzle:
- @docusaurus/theme-classic
- @docusaurus/plugin-debug
```

### PR DESCRIPTION
**Pull request by Danielku15**
Fixes #85 
Fixes #87

Adapted the following three aspects to make this plugin work again with the latest released Docusaurus:

1. Updated readme steps to register the plugin before the swizzle. Swizzle is only possible for registered plugins. 
2. Flatten file hierarchy because swizzle is not allowed for nested hierarchies anymore. See [here](https://github.com/facebook/docusaurus/blob/9c92a79d23533a61f3ad1bf3ea4d0889f0e2710f/packages/docusaurus/src/commands/swizzle/actions.ts#L65-L70) for ignore on nested files when globbing. 
3. Fix `getFilePaths` because latest Docusaurus rather generates `route/index.html` files instead of `route.html` in latest versions. 
4. In case you have configured your `baseUrl` to `/` the URLs for the search result would end up with a link like `//docs` which confused the React router. Added some additional handling on this scenario.

### CODE REVIEW

**Comment by Danielku15** [comment]
Ping @praveenn77 would be amazing if we can get this merged and released in a docusaurus-lunr-search 2.2.1

**Review by OscarFlowize — COMMENTED** [review]
It works! Thank you!

**Comment by praveenn77** [comment]
@Danielku15  Thank you for your contirbution

**Comment by sg-chris** [comment]
Thank you!!

**Comment by daddykotex** [comment]
I've opened https://github.com/praveenn77/docusaurus-lunr-search/pull/89 and I think it build on top of this PR. Adding support when the baseUrl is not the default.

**Pull request merged**
